package com.dnaevolutions.moldqueen.core

import org.json.JSONObject
import kotlin.math.abs
import kotlin.math.floor

/**
 * Channel map: function -> (slot, channel, value) resolution + validation + migration.
 *
 * Clean-room Kotlin port of linux-core/mk4web/channelmap.py — reproduces its OBSERVABLE
 * behavior exactly (parity-tested against 510 vectors generated by that module),
 * including Python's int-vs-float `isinstance` checks and round-half-to-even rounding.
 *
 * Maps are org.json.JSONObject (Android's impl preserves key/parse order via
 * LinkedHashMap, matching the Pi's dict ordering on the wire).
 */
object ChannelMap {

    private val REQUIRED_KEYS = listOf("slot", "channel", "invert")
    val LANGS = listOf("en", "de", "zh", "ko", "es", "fr")

    // ---- resolution -------------------------------------------------------------

    /**
     * function + signed value (-7..7) -> [slot, channel, out_value], or null.
     * Order (mirrors channelmap.resolve): device_swap (slot 0<->1) → reverse_scale
     * trim on the PRE-invert reverse input → invert → per-direction max cap.
     */
    fun resolve(mp: JSONObject, function: String?, value: Int, deviceSwap: Boolean = false): IntArray? {
        if (function == null) return null
        val fns = mp.optJSONObject("functions") ?: return null
        val a = fns.optJSONObject(function) ?: return null
        var slot = pyInt(a.opt("slot")) ?: return null
        val ch = pyInt(a.opt("channel")) ?: return null
        if (deviceSwap && (slot == 0 || slot == 1)) slot = 1 - slot
        val v = value
        var mag = abs(v)
        if (v < 0) {
            val rs = numberOrNull(a.opt("reverse_scale"))
            if (rs != null && rs != 1.0) mag = maxOf(0, minOf(7, pyRound(mag * rs)))
        }
        var sign = if (v < 0) -1 else if (v > 0) 1 else 0
        if (truthy(a.opt("invert"))) sign = -sign
        var out = sign * mag
        if (out > 0) out = minOf(out, cap(a, "max_fwd", 7))
        else if (out < 0) out = -minOf(-out, cap(a, "max_rev", 5))
        return intArrayOf(slot, ch, out)
    }

    private fun cap(a: JSONObject, key: String, default: Int): Int {
        intIn(a.opt(key), 1, 7)?.let { return it }
        intIn(a.opt("max"), 1, 7)?.let { return it }   // legacy symmetric `max`
        return default
    }

    // ---- validation -------------------------------------------------------------

    /**
     * -> Pair(ok, errors). If [functions] is given the map must define EXACTLY those;
     * otherwise validates whatever the map declares. Error strings match channelmap.py.
     */
    fun validate(mp: Any?, functions: List<String>? = null): Pair<Boolean, List<String>> {
        val errs = mutableListOf<String>()
        if (mp !is JSONObject || mp.optJSONObject("functions") == null) {
            return false to listOf("map must be an object with a 'functions' object")
        }
        val fns = mp.getJSONObject("functions")
        val expected = functions?.toList() ?: fns.keys().asSequence().toList()
        val seen = HashMap<Pair<Int, Int>, String>()
        for (f in expected) {
            val a = fns.opt(f)
            if (a !is JSONObject) { errs.add("missing function '$f'"); continue }
            for (k in REQUIRED_KEYS) if (!a.has(k)) errs.add("$f: missing '$k'")
            val slot = a.opt("slot"); val ch = a.opt("channel")
            if (!(slot is Int && slot in 0..2)) errs.add("$f: slot must be an integer 0-2")
            if (!(ch is Int && ch in 0..3)) errs.add("$f: channel must be an integer 0-3")
            if (a.opt("invert") !is Boolean) errs.add("$f: invert must be true/false")
            for (mk in listOf("max_fwd", "max_rev", "max")) if (a.has(mk)) {
                if (intIn(a.opt(mk), 1, 7) == null) errs.add("$f: $mk must be an integer 1-7")
            }
            if (a.has("reverse_scale")) {
                val rs = numberOrNull(a.opt("reverse_scale"))
                if (rs == null || rs < 0.25 || rs > 4.0) errs.add("$f: reverse_scale must be a number 0.25-4.0")
            }
            if (a.has("labels")) {
                val lb = a.opt("labels")
                if (lb !is JSONObject) errs.add("$f: labels must be an object")
                else for (lang in lb.keys()) if (lb.opt(lang) !is String) errs.add("$f: labels.$lang must be text")
            }
            for (k in listOf("label_en", "label_de")) if (a.has(k) && a.opt(k) !is String) errs.add("$f: $k must be text")
            if (slot is Int && ch is Int) {
                val key = slot to ch
                val dup = seen[key]
                if (dup != null) errs.add("$f: duplicate slot $slot/channel $ch (already used by '$dup')")
                else seen[key] = f
            }
        }
        if (functions != null) {
            val extra = fns.keys().asSequence().filter { it !in expected }.sorted().toList()
            if (extra.isNotEmpty()) errs.add("unknown functions: " + extra.joinToString(", "))
        }
        return errs.isEmpty() to errs
    }

    // ---- migration --------------------------------------------------------------

    /** Upgrade a map in place (labels object + per-direction caps); idempotent. */
    fun migrate(mp: JSONObject): JSONObject {
        val fns = mp.optJSONObject("functions") ?: return mp
        for (f in fns.keys().asSequence().toList()) {
            val a = fns.optJSONObject(f) ?: continue
            migrateLabels(a)
            migrateCaps(a)
        }
        return mp
    }

    private fun migrateLabels(a: JSONObject) {
        val labels = a.optJSONObject("labels") ?: JSONObject()
        if (!labels.has("en") && a.opt("label_en") is String) labels.put("en", a.getString("label_en"))
        if (!labels.has("de") && a.opt("label_de") is String) labels.put("de", a.getString("label_de"))
        val out = JSONObject()
        for (L in LANGS) out.put(L, if (labels.opt(L) is String) labels.getString(L) else "")
        a.put("labels", out)
        a.remove("label_en"); a.remove("label_de")
    }

    private fun migrateCaps(a: JSONObject) {
        val legacy = intIn(a.opt("max"), 1, 7)
        if (!a.has("max_fwd")) a.put("max_fwd", legacy ?: 7)
        if (!a.has("max_rev")) a.put("max_rev", legacy ?: 5)
        a.remove("max")
        for ((k, d) in listOf("max_fwd" to 7, "max_rev" to 5)) {
            if (intIn(a.opt(k), 1, 7) == null) a.put(k, d)
        }
    }

    // ---- load / placeholder -----------------------------------------------------

    fun functionsOf(mp: JSONObject?): List<String> =
        mp?.optJSONObject("functions")?.keys()?.asSequence()?.toList() ?: emptyList()

    /** Load + migrate + validate [jsonText] against [functions]; placeholder on error. */
    fun load(jsonText: String?, functions: List<String>?): JSONObject {
        val mp = try {
            JSONObject(jsonText ?: throw IllegalArgumentException("null"))
        } catch (e: Exception) {
            return placeholderMap(functions ?: emptyList())
        }
        migrate(mp)
        val (ok, _) = validate(mp, functions)
        return if (ok) mp else placeholderMap(functions ?: emptyList())
    }

    fun placeholderMap(functions: List<String>): JSONObject {
        val fns = JSONObject()
        functions.forEachIndexed { i, f ->
            val title = f.split("_").joinToString(" ") { p -> p.replaceFirstChar { it.uppercase() } }
            val labels = JSONObject(); for (L in LANGS) labels.put(L, title)
            fns.put(f, JSONObject()
                .put("slot", i / 4).put("channel", i % 4).put("invert", false)
                .put("max_fwd", 7).put("max_rev", 5).put("reverse_scale", 1.0)
                .put("labels", labels).put("confirmed", false))
        }
        return JSONObject().put("version", 1).put("functions", fns)
    }

    // ---- python-semantics helpers ----------------------------------------------

    /** Round half-to-even (Python 3 round()), for non-negative inputs. */
    private fun pyRound(x: Double): Int {
        val f = floor(x)
        val diff = x - f
        val r = when {
            diff < 0.5 -> f
            diff > 0.5 -> f + 1
            else -> if (f.toLong() % 2L == 0L) f else f + 1
        }
        return r.toInt()
    }

    /** Mimic Python int(): truncates floats toward zero, bool->0/1, parses int strings. */
    private fun pyInt(v: Any?): Int? = when (v) {
        is Boolean -> if (v) 1 else 0
        is Int -> v
        is Long -> v.toInt()
        is Double -> v.toInt()
        is Float -> v.toInt()
        is String -> v.trim().toIntOrNull()
        else -> null
    }

    /** Python isinstance(x,(int,float)) and not bool -> Double, else null. */
    private fun numberOrNull(v: Any?): Double? = when (v) {
        is Boolean -> null
        is Int -> v.toDouble()
        is Long -> v.toDouble()
        is Float -> v.toDouble()
        is Double -> v
        is java.math.BigDecimal -> v.toDouble()
        is java.math.BigInteger -> v.toDouble()
        else -> null
    }

    /** Python isinstance(x,int) and not bool and lo<=x<=hi -> Int, else null. */
    private fun intIn(v: Any?, lo: Int, hi: Int): Int? = when (v) {
        is Int -> if (v in lo..hi) v else null
        is Long -> if (v in lo.toLong()..hi.toLong()) v.toInt() else null
        else -> null
    }

    /** Python truthiness for the `invert` gate. */
    private fun truthy(v: Any?): Boolean = when (v) {
        null, JSONObject.NULL -> false
        is Boolean -> v
        is Number -> v.toDouble() != 0.0
        is String -> v.isNotEmpty()
        else -> true
    }
}
